import assert from 'node:assert/strict'
import test from 'node:test'
import pg from 'pg'
import { buildServer } from '../src/app.js'
import { authenticate } from './auth-helper.js'
import { privateDatabase } from './private-database.js'

/* The three endpoints against real PostGIS, because everything that can go
 * quietly wrong here is a property of the database and not of the JavaScript:
 *
 *   The accent fold. `search_name` is generated by `place_searchable()` and
 *   the trigram index is on it. A query that folds any other way returns an
 *   empty list — not an error, an empty list — so "cafe zoom" finding
 *   "Café Zoöm" is the assertion that the index and the lookup agree, and it
 *   can only be made against the real function.
 *
 *   The redirects. A stop keeps a place id for the life of a trip and upstream
 *   reissues ids monthly. A merged place must still open by its old id, and a
 *   closed one must say it closed rather than 404 — two different answers a
 *   traveller can act on.
 *
 *   The widening. A sparse area must not return an empty list; the radius
 *   grows and the floor drops in the documented steps, and the response says
 *   which radius it ended up using.
 *
 * Its own database, named for this file rather than for the layer: this file
 * resets the schema, so does places-ingest.test.js, and the runner runs them
 * at the same time. Two files sharing one name here is three unrelated
 * assertions failing in whichever lost the race. See private-database.js.
 */

const baseUrl =
  process.env.TEST_DATABASE_URL || 'postgres://postgres:postgres@127.0.0.1:55432/wayfare_test'

const moduleUnderTest = await import('../src/postgres.js').catch(() => null)

let databaseUrl = baseUrl
const reachable = await (async () => {
  if (!moduleUnderTest) return 'no postgres module'
  const client = new pg.Client({ connectionString: baseUrl })
  try {
    await client.connect()
    await client.end()
  } catch {
    return 'no PostgreSQL to test against'
  }
  databaseUrl = await privateDatabase(baseUrl, 'placesapi')
  return false
})()

const AMSTERDAM = { lng: 4.8852, lat: 52.36, cell: 'N52E004' }
/* The middle of a one-degree cell on the prairies, so even the widest rung of
   the ladder stays inside one cell and the test is about widening rather than
   about coverage. */
const PRAIRIE = { lng: -105.5, lat: 50.5, cell: 'N50W106' }

/* Ten places above the confidence floor within a few hundred metres, because
   `widen` stops as soon as a rung finds eight: fewer and the happy path would
   be quietly testing the sparse path instead. */
const SEED = [
  ['Rijksmuseum', 'museum', 4.8852, 52.36, 0.93, 'art_museum'],
  ['Café Zoöm', 'cafe', 4.886, 52.3608, 0.71, 'coffee_shop'],
  ['Van Gogh Museum', 'museum', 4.8811, 52.3584, 0.88, 'art_museum'],
  ['Moco Museum', 'museum', 4.8817, 52.3591, 0.74, 'art_museum'],
  ['Museumplein', 'sights', 4.8796, 52.3576, 0.8, 'public_plaza'],
  ['Concertgebouw', 'entertainment', 4.8792, 52.3562, 0.86, 'concert_hall'],
  ['Stedelijk Museum', 'gallery', 4.8797, 52.358, 0.82, 'art_gallery'],
  ['Wasserette De Zeep', 'services', 4.8854, 52.3602, 0.64, 'laundry'],
  ['Broodje Van Gogh', 'food', 4.8843, 52.3597, 0.62, 'sandwich_shop'],
  ['Bar Vondel', 'bar', 4.8775, 52.3583, 0.69, 'bar'],
  /* Under the 0.3 floor: a duplicate or a defunct shop, and never shown. */
  ['Rijksmuseum (dup)', 'museum', 4.8853, 52.3601, 0.12, 'art_museum'],
]

async function seed(client) {
  const ids = new Map()
  for (const [name, category, lng, lat, confidence, raw] of SEED) {
    const inserted = await client.query(
      `insert into places
        (gers_id, name, alternate_names, geom, category, category_raw, address, website, phone,
         confidence, operating, cell)
       values ($1,$2,$3, ST_SetSRID(ST_MakePoint($4,$5),4326)::geography, $6,$7,$8::jsonb,$9,$10,$11,$12,$13)
       returning id`,
      [
        `overture:${name.toLowerCase().replaceAll(/[^a-z]+/g, '-')}`,
        name,
        [],
        lng,
        lat,
        category,
        raw,
        JSON.stringify({ freeform: 'Museumstraat 1', locality: 'Amsterdam', country: 'NL' }),
        null,
        null,
        confidence,
        'open',
        'N52E004',
      ],
    )
    ids.set(name, inserted.rows[0].id)
  }

  /* One grain elevator, six kilometres away, alone in its cell. */
  const prairie = await client.query(
    `insert into places (gers_id, name, geom, category, category_raw, confidence, cell)
     values ($1,$2, ST_SetSRID(ST_MakePoint($3,$4),4326)::geography, $5,$6,$7,$8) returning id`,
    [
      'overject:elevator',
      'Pioneer Grain Elevator',
      PRAIRIE.lng + 0.0847,
      PRAIRIE.lat,
      'historic',
      'historic_site',
      0.55,
      PRAIRIE.cell,
    ],
  )
  ids.set('Pioneer Grain Elevator', prairie.rows[0].id)

  /* Two sources on one record, one of them OpenStreetMap — which is the whole
     point of carrying the trail: ODbL obliges us to attribute and CDLA does
     not, and the response has to say which applies to which record. */
  await client.query(
    `insert into place_sources (place_id, source, license, upstream_id, version, confidence, fields)
     values ($1,'overture','CDLA-Permissive-2.0','ov-rijks','2026-08-19.0',0.93,'{name,category}'),
            ($1,'osm','ODbL-1.0','w12345','2026-08-19.0',0.9,'{website,phone}')`,
    [ids.get('Rijksmuseum')],
  )
  await client.query(
    `insert into place_sources (place_id, source, license, upstream_id, version, confidence, fields)
     values ($1,'overture','CDLA-Permissive-2.0','ov-zoom','2026-08-19.0',0.71,'{name}')`,
    [ids.get('Café Zoöm')],
  )

  for (const cell of [AMSTERDAM.cell, PRAIRIE.cell]) {
    const [ns, latitude, ew, longitude] = [
      cell[0],
      Number(cell.slice(1, 3)),
      cell[3],
      Number(cell.slice(4)),
    ]
    const south = (ns === 'S' ? -1 : 1) * latitude
    const west = (ew === 'W' ? -1 : 1) * longitude
    await client.query(
      `insert into place_coverage (cell, west, south, east, north, status, versions, place_count, last_refresh)
       values ($1,$2,$3,$4,$5,'ready','{"overture":"2026-08-19.0"}'::jsonb,$6, now())`,
      [cell, west, south, west + 1, south + 1, cell === AMSTERDAM.cell ? SEED.length : 1],
    )
  }
  return ids
}

async function world(t, server = {}) {
  const admin = new pg.Client({ connectionString: databaseUrl })
  await admin.connect()
  await admin.query('drop schema public cascade; create schema public')
  await admin.end()

  const repository = await moduleUnderTest.createPostgresRepository({
    databaseUrl,
    adminEmail: 'owner@example.com',
  })
  t.after(() => repository.close())
  await repository.migrate()

  const client = new pg.Client({ connectionString: databaseUrl })
  await client.connect()
  t.after(() => client.end())
  const ids = await seed(client)

  const app = await buildServer({
    repository,
    mailer: { async send() {} },
    publicUrl: 'https://offwego.example.com',
    sessionSecret: 'test-secret-that-is-long-enough',
    ...server,
  })
  t.after(() => app.close())
  const authorization = await authenticate(repository, 'owner@example.com')
  const get = (url, headers = { authorization }) => app.inject({ method: 'GET', url, headers })
  return { app, repository, client, ids, authorization, get }
}

test('search finds a place by name, with its provenance', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get('/api/places/search?q=rijks')
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.degraded, false)
  assert.equal(body.places[0].name, 'Rijksmuseum')
  assert.equal(body.places[0].category, 'museum')
  assert.equal(body.places[0].confidence, 0.93)
  /* Every record says who told us and under what licence. */
  assert.deepEqual(
    body.places[0].sources.map(source => [source.source, source.license, source.upstreamId]),
    [
      ['osm', 'ODbL-1.0', 'w12345'],
      ['overture', 'CDLA-Permissive-2.0', 'ov-rijks'],
    ],
  )
  /* And the notices the client has to render — ODbL, because one of them is
     OpenStreetMap's. */
  assert.ok(
    body.places[0].attribution.some(
      notice => notice.license === 'ODbL-1.0' && /OpenStreetMap/.test(notice.notice),
    ),
    'ODbL notice travels with the record',
  )
  /* A typeahead is re-issued per keystroke; the cache is short and private. */
  assert.equal(response.headers['cache-control'], 'private, max-age=30')
})

test('search folds accents and case, both ways', { skip: reachable }, async t => {
  const { get } = await world(t)
  const plain = await get('/api/places/search?q=cafe%20zoom')
  assert.equal(plain.statusCode, 200)
  assert.equal(
    plain.json().places[0]?.name,
    'Café Zoöm',
    'unaccented letters find the accented name',
  )
  const accented = await get(`/api/places/search?q=${encodeURIComponent('CAFÉ ZOÖM')}`)
  assert.equal(accented.json().places[0]?.name, 'Café Zoöm', 'and the accented letters do too')
})

test('search biased to a trip still finds what is far away', { skip: reachable }, async t => {
  const { get, repository } = await world(t)
  const user = await repository.ensureUser('owner@example.com')
  const trip = await repository.createTrip(user, { title: 'Amsterdam' })
  await repository.createStop(user, trip.id, {
    name: 'Hotel',
    icon: 'pin',
    status: 'planned',
    lng: AMSTERDAM.lng,
    lat: AMSTERDAM.lat,
  })
  const near = await get(`/api/places/search?q=museum&trip_id=${trip.id}`)
  assert.equal(near.statusCode, 200)
  assert.ok(
    near.json().places.some(place => place.name === 'Van Gogh Museum'),
    'the trip geography is searched',
  )
  /* A trip nobody is on is not a search scope. */
  const other = await authenticate(repository, 'stranger@example.com')
  const refused = await get(`/api/places/search?q=museum&trip_id=${trip.id}`, {
    authorization: other,
  })
  assert.equal(refused.statusCode, 404)
})

test('nearby ranks by kind and distance together', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=1000`,
  )
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.degraded, false)
  assert.equal(body.widened, 0, 'ten places within the radius is enough')
  assert.equal(body.radius, 1000)
  const names = body.places.map(place => place.name)
  assert.equal(names[0], 'Rijksmuseum')
  /* The launderette is nearer than half the list and still below it. */
  assert.ok(
    names.indexOf('Wasserette De Zeep') > names.indexOf('Van Gogh Museum'),
    'a museum eight hundred metres away beats a launderette underfoot',
  )
  /* Under the floor is not shown at all, rather than shown last: a
     0.12-confidence duplicate on a map is worse than no pin. */
  assert.ok(!names.includes('Rijksmuseum (dup)'), 'the confidence floor suppresses, not demotes')
  assert.equal(response.headers['cache-control'], 'private, max-age=120')
  assert.ok(body.places.every(place => Number.isFinite(place.metres)))
})

test('nearby filters by category, and refuses one it does not know', {
  skip: reachable,
}, async t => {
  const { get } = await world(t)
  const museums = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=1000&category=museum`,
  )
  assert.equal(museums.statusCode, 200)
  assert.deepEqual(
    [...new Set(museums.json().places.map(place => place.category))],
    ['museum'],
    'only the category asked for',
  )
  const nonsense = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&category=nightclubs`,
  )
  assert.equal(nonsense.statusCode, 400)
})

test('a sparse area widens rather than returning nothing', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get(`/api/places/nearby?lat=${PRAIRIE.lat}&lng=${PRAIRIE.lng}&radius=1000`)
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.places.length, 1, 'the one real place, not an empty list and not an invention')
  assert.equal(body.places[0].name, 'Pioneer Grain Elevator')
  assert.ok(body.widened > 0, 'the ladder was climbed')
  assert.ok(body.radius > 1000, 'and the answer says how far it had to go')
  assert.ok(body.radius <= 50_000, 'but never past where "nearby" stops meaning anything')
})

test('a silly radius or limit is capped, not refused', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=9000000&limit=5000`,
  )
  assert.equal(response.statusCode, 200)
  assert.ok(response.json().radius <= 50_000)
  assert.ok(response.json().places.length <= 50)
  /* Letters where a number goes is a bug in the caller, and says so. */
  assert.equal((await get('/api/places/nearby?lat=here&lng=4.8')).statusCode, 400)
  assert.equal((await get('/api/places/nearby?lat=52.36')).statusCode, 400)
})

test('one place, in full, with its sources', { skip: reachable }, async t => {
  const { get, ids } = await world(t)
  const response = await get(`/api/places/${ids.get('Rijksmuseum')}`)
  assert.equal(response.statusCode, 200)
  const { place, redirectedFrom } = response.json()
  assert.equal(redirectedFrom, null)
  assert.equal(place.name, 'Rijksmuseum')
  assert.equal(place.address.locality, 'Amsterdam')
  assert.equal(place.sources.length, 2)
  assert.ok(place.attribution.length >= 2)
  /* A record changes with a monthly ingest; a day is already far shorter than
     the data's own life. */
  assert.equal(response.headers['cache-control'], 'private, max-age=86400')
  assert.equal((await get('/api/places/not a uuid at all')).statusCode, 400)
  assert.equal(
    (await get('/api/places/3f0c8f0e-1111-4111-8111-111111111111')).statusCode,
    404,
    'an id nobody has ever heard of is a plain not-found',
  )

  /* And the upstream id opens the same door, because it is the only id a
     degraded answer can carry: a stop filed from a fallback list must open
     once its cell has been ingested, without the client knowing which kind of
     answer it came from. */
  const byUpstream = await get(`/api/places/${encodeURIComponent(place.gersId)}`)
  assert.equal(byUpstream.statusCode, 200)
  assert.equal(byUpstream.json().place.id, ids.get('Rijksmuseum'))
  assert.equal((await get('/api/places/overture:nobody')).statusCode, 404)
})

test('a place that moved still resolves by its old id', { skip: reachable }, async t => {
  const { get, client, ids } = await world(t)
  const moved = '11111111-2222-4333-8444-555555555555'
  const alsoMoved = '11111111-2222-4333-8444-666666666666'
  /* Two dead ids pointing at one survivor, which is what a three-way merge
     leaves behind. Migration 043 makes `new_id` a foreign key into `places`,
     so a redirect can only ever point at a row that exists: a chain through a
     vanished intermediate is unrepresentable, and the hop limit in store.js is
     there against a bad ingest rather than against the normal case. */
  await client.query(
    `insert into place_redirects (old_id, new_id, reason) values ($1,$3,'merged'), ($2,$3,'merged')`,
    [moved, alsoMoved, ids.get('Rijksmuseum')],
  )
  for (const old of [moved, alsoMoved]) {
    const response = await get(`/api/places/${old}`)
    assert.equal(response.statusCode, 200)
    assert.equal(response.json().place.id, ids.get('Rijksmuseum'))
    assert.equal(response.json().redirectedFrom, old, 'and says which id it came in on')
    assert.ok(response.json().place.sources.length, 'the successor arrives whole')
  }
})

test('a place that closed says so, and does not 404', { skip: reachable }, async t => {
  const { get, client } = await world(t)
  const closed = '99999999-2222-4333-8444-555555555555'
  await client.query(
    `insert into place_redirects (old_id, new_id, reason) values ($1, null, 'closed')`,
    [closed],
  )
  const response = await get(`/api/places/${closed}`)
  assert.equal(response.statusCode, 410, 'gone, which is a different fact from never existed')
  assert.equal(response.json().gone, true)
  assert.equal(response.json().reason, 'closed')
})

test('every route is behind the same login as the rest of /api', { skip: reachable }, async t => {
  const { app, get, ids } = await world(t)
  for (const url of [
    '/api/places/search?q=rijks',
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}`,
    `/api/places/${ids.get('Rijksmuseum')}`,
  ]) {
    const anonymous = await app.inject({ method: 'GET', url })
    assert.equal(anonymous.statusCode, 401, `${url} refuses an unsigned request`)
    assert.equal(anonymous.json().error, 'Sign in required')
    const wrong = await app.inject({
      method: 'GET',
      url,
      headers: { authorization: 'Bearer nonsense' },
    })
    assert.equal(wrong.statusCode, 401, `${url} refuses a bad token`)
  }
  assert.equal((await get('/api/places/search?q=rijks')).statusCode, 200)
})

/* The bug that made the whole third tier dead on arrival, and that no test
   caught because every test either stubbed `placeSources` or ran with the
   fallback switched off.
 *
 * A degraded record's id is its upstream GERS id, not one of our uuids —
 * deliberately, so a stop can hold it and go on resolving once the cell
 * lands. The route then asked the database for those ids' sources, and
 * `place_id = any($1::uuid[])` raised 22P02 from inside the driver. Every
 * degraded answer was a 500: a traveller in a country nobody had ingested
 * got an error rather than a thinner list. */
test('a degraded record is served, not 500ed, though its id is not one of ours', {
  skip: reachable,
}, async t => {
  const bucket = {
    id: 'ov-degraded-1',
    gersId: 'ov-degraded-1',
    name: 'Somewhere Upstream Knows',
    lng: 139.7454,
    lat: 35.6586,
    category: 'museum',
    confidence: 0.9,
    metres: 10,
    sources: [{ source: 'overture', license: 'ODbL-1.0', upstreamId: 'osm:1', version: 'v' }],
  }
  /* The bucket is the only stub: what is being proved is what the route does
     with a record whose id is not a uuid, not how Parquet is read. */
  const { get } = await world(t, {
    placesFallback: {
      available: true,
      async readBounds() {
        return { places: [bucket], degraded: true, reason: null, cells: ['N35E139'] }
      },
      inFlight: () => 0,
    },
  })
  const response = await get('/api/places/nearby?lat=35.6586&lng=139.7454&radius=500&limit=5')
  assert.equal(response.statusCode, 200, response.body)
  const body = response.json()
  assert.equal(body.degraded, true)
  const found = body.places.find(place => place.id === 'ov-degraded-1')
  assert.ok(found, `the degraded record is missing from ${JSON.stringify(body.places)}`)
  /* And it carries its own licence through, which is the whole reason the
     record travels with its sources rather than being looked up. */
  assert.deepEqual(
    found.attribution.map(notice => notice.license),
    ['ODbL-1.0'],
  )
  assert.equal(response.headers['cache-control'], 'no-store')

  /* The same through search, which has its own call to the same helper. */
  const named = await get('/api/places/search?q=Somewhere&near=139.7454,35.6586')
  assert.equal(named.statusCode, 200, named.body)
  assert.equal(named.json().degraded, true)
})

/* The map's pin layer.
 *
 * What it replaced held the Netherlands and Scotland — the only two regions
 * the Wikipedia seeder was ever pointed at — and everywhere else the map asked
 * Wikipedia live from the phone. This answers anywhere from one indexed query,
 * and the ordering is the point: a viewport has no centre to measure from, so
 * the category weighting is the whole ranking and it has to put the museum
 * above the launderette. */
test('a viewport draws the best of what is in it, not the first rows found', {
  skip: reachable,
}, async t => {
  const { app } = await world(t)
  const box = 'west=4.87&south=52.35&east=4.89&north=52.37'
  const view = async query => {
    const reply = await app.inject({ method: 'GET', url: `/api/places/in-view?${query}` })
    assert.equal(reply.statusCode, 200, reply.body)
    return reply.json()
  }

  const all = await view(box)
  const names = all.places.map(place => place.name)
  assert.ok(names.includes('Van Gogh Museum'), names.join(', '))
  /* Below the confidence floor, so never drawn — the same floor every other
     query uses. */
  assert.ok(!names.includes('Rijksmuseum (dup)'), 'a 0.12-confidence duplicate is a pin')
  /* The museums and the gallery come before the laundry, whatever order the
     table happens to hold them in. */
  const museum = names.indexOf('Van Gogh Museum')
  const laundry = names.indexOf('Wasserette De Zeep')
  if (laundry >= 0) assert.ok(museum < laundry, `${names.join(' < ')}`)

  /* Zoomed out: only what is worth a dot from orbit. */
  const headline = await view(`${box}&headline=true`)
  assert.ok(headline.places.length > 0)
  assert.ok(headline.places.length < all.places.length, 'headline drew everything')
  for (const place of headline.places) assert.equal(place.big, true)
  assert.ok(
    !headline.places.some(place => place.category === 'services'),
    'a launderette survived a zoom out',
  )

  /* One attribution for the layer, which is how a map carries it, rather than
     a provenance trail per pin. */
  assert.ok(Array.isArray(all.attribution))
  for (const notice of all.attribution) assert.ok(notice.notice, JSON.stringify(notice))

  /* A pin is a dot and a label, plus the two numbers that decide how it is
     drawn. The rest of a place is one tap away, and sending it for three
     hundred pins is bytes nobody renders.
     `minzoom` and `rank` are here rather than one tap away because they are
     not about the place, they are about the drawing of it, and the map needs
     every pin's before it can draw any of them — see places/rank.js. */
  assert.deepEqual(Object.keys(all.places[0]).sort(), [
    'big',
    'category',
    'confidence',
    'id',
    'lat',
    'lng',
    'minzoom',
    'name',
    'rank',
  ])

  /* And they are numbers the map layer can actually use: a zoom inside the
     range the camera moves through, and a positive integer to sort by. */
  for (const place of all.places) {
    assert.ok(place.minzoom >= 11 && place.minzoom <= 18, `${place.name} draws at ${place.minzoom}`)
    assert.ok(Number.isInteger(place.rank) && place.rank > 0, `${place.name} ranks ${place.rank}`)
  }

  /* Public, like the layer it replaces: a map's pins are built from nobody's
     trip and carry nothing private. */
  const anonymous = await app.inject({ method: 'GET', url: `/api/places/in-view?${box}` })
  assert.equal(anonymous.statusCode, 200)

  /* And a box that is not a box is refused rather than guessed at. */
  const upsideDown = await app.inject({
    method: 'GET',
    url: '/api/places/in-view?west=4&south=53&east=5&north=52',
  })
  assert.equal(upsideDown.statusCode, 400)
})

test('an uncovered cell is asked for, and the answer says it is thin', {
  skip: reachable,
}, async t => {
  const { get, client } = await world(t)
  /* Tokyo: no coverage row at all, and nothing in `places`. */
  const response = await get('/api/places/nearby?lat=35.6586&lng=139.7454&radius=500')
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.degraded, true)
  assert.equal(body.coverage.cell, 'N35E139')
  assert.deepEqual(body.places, [])
  /* Degraded answers must not be cached: the cell is being ingested now. */
  assert.equal(response.headers['cache-control'], 'no-store')
  const queued = await client.query(
    'select cell, status, requested_at from place_coverage where cell=$1',
    ['N35E139'],
  )
  assert.equal(queued.rows[0].status, 'pending', 'the miss put the cell on the queue')
  assert.ok(queued.rows[0].requested_at, 'with the moment it was asked for, so it can be ordered')

  /* Asking again does not move it to the back of the queue. */
  const first = queued.rows[0].requested_at
  await get('/api/places/nearby?lat=35.6586&lng=139.7454&radius=500')
  const again = await client.query('select requested_at from place_coverage where cell=$1', [
    'N35E139',
  ])
  assert.deepEqual(again.rows[0].requested_at, first, 'requested_at keeps the earliest ask')
})

test('a ready cell is never knocked back to pending by a query', { skip: reachable }, async t => {
  const { get, client } = await world(t)
  await get(`/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=1000`)
  const row = await client.query('select status from place_coverage where cell=$1', [
    AMSTERDAM.cell,
  ])
  assert.equal(row.rows[0].status, 'ready')
})

/* A tile of places, which is the shape the map actually asks in.
 *
 * Reported from the road: the map was janky and finnicky. It was, and the
 * cause was not the ranking — it was that a viewport is a different question
 * every time the camera moves, so a pan got a different best-of and dots at
 * the edges appeared and vanished. A tile is the same question with a fixed
 * frame: z/x/y, decided once, the same for everybody, cacheable.
 *
 * This is the test that has to exist because the SQL behind it cannot run
 * without PostGIS, and PostGIS is not in the sandbox this is written in.
 * ST_TileEnvelope, ST_AsMVTGeom and ST_AsMVT are three chances to be wrong
 * about a projection and nothing but a real database will say so. */
test('a tile of places is real vector tile bytes, and knows its own zoom', {
  skip: reachable,
}, async t => {
  const { app, repository } = await world(t)
  const ask = (sql, args) => repository.pool.query(sql, args)
  /* The tile over central Amsterdam at zoom 14, worked out from the slippy
     grid rather than copied: x = (lng + 180) / 360 * 2^z. */
  const z = 14
  const x = Math.floor(((AMSTERDAM.lng + 180) / 360) * 2 ** z)
  const rad = (AMSTERDAM.lat * Math.PI) / 180
  const y = Math.floor(((1 - Math.log(Math.tan(rad) + 1 / Math.cos(rad)) / Math.PI) / 2) * 2 ** z)

  const tile = await app.inject({ method: 'GET', url: `/api/places/tiles/${z}/${x}/${y}` })
  assert.equal(tile.statusCode, 200, tile.body)
  assert.match(tile.headers['content-type'], /vnd\.mapbox-vector-tile/)
  /* Cached hard and publicly: a tile carries nothing of anybody's trip, and
     the second look at a square costing nothing is half of why a tiled map
     does not flicker. */
  assert.match(tile.headers['cache-control'], /public/)
  assert.ok(tile.rawPayload.length > 0, 'central Amsterdam is not an empty tile')

  /* The same square, asked for twice, is the same bytes. This is the whole
     property the jank was the absence of: a viewport query answered a moved
     camera differently every time, and a tile cannot. */
  const again = await app.inject({ method: 'GET', url: `/api/places/tiles/${z}/${x}/${y}` })
  assert.deepEqual(again.rawPayload, tile.rawPayload)

  /* Zoomed out far enough, the everyday places have not earned their dot yet,
     so the same ground carries fewer of them. Compared by size rather than by
     decoding the protobuf: fewer features is fewer bytes, and a decoder is a
     dependency this suite does not need to make the point. */
  const wide = await app.inject({
    method: 'GET',
    url: `/api/places/tiles/12/${Math.floor(x / 4)}/${Math.floor(y / 4)}`,
  })
  assert.ok([200, 204].includes(wide.statusCode), wide.body)

  /* A square outside the grid of its zoom is a bug in a client, not an empty
     part of the world. */
  const nowhere = await app.inject({ method: 'GET', url: `/api/places/tiles/2/9/0` })
  assert.equal(nowhere.statusCode, 404)
  const nonsense = await app.inject({ method: 'GET', url: '/api/places/tiles/99/0/0' })
  assert.equal(nonsense.statusCode, 400)

  /* Public, like the viewport query it replaces: a map's pins are built from
     nobody's trip. The inject above carries no session at all, and it was a
     200 — which is the assertion. */
  const ocean = await app.inject({ method: 'GET', url: '/api/places/tiles/14/8000/8000' })
  assert.ok([200, 204].includes(ocean.statusCode), ocean.body)

  /* A square over ground nobody has ingested is answered and then forgotten.
   *
   * This is the bug that was reported as pins at one zoom and nothing a zoom
   * in, never healing. A tile over a cell with no coverage builds empty —
   * correctly, we hold nothing there — and keeping that emptiness is how a
   * city that fills in half an hour goes on looking empty for a day: the row
   * could only be removed by an ingest of that exact ground, and the browser
   * held it for an hour with a day of stale-while-revalidate behind it.
   *
   * Somewhere in the Pacific, which no fixture has ever loaded. */
  const unknown = { z: 14, x: 1000, y: 8000 }
  const cold = await app.inject({
    method: 'GET',
    url: `/api/places/tiles/${unknown.z}/${unknown.x}/${unknown.y}`,
  })
  assert.ok([200, 204].includes(cold.statusCode), cold.body)
  assert.equal(cold.headers['cache-control'], 'no-store', 'unfinished ground is never cached')
  const held = await ask(
    'select count(*)::int as n from place_tiles where z = $1 and x = $2 and y = $3',
    [unknown.z, unknown.x, unknown.y],
  )
  assert.equal(held.rows[0].n, 0, 'and it left nothing behind to be wrong with')

  /* The Amsterdam square, whose cell the fixture did load, is kept — which is
     the other half: this is a cache, and it has to still be one. */
  const kept = await ask(
    'select count(*)::int as n from place_tiles where z = $1 and x = $2 and y = $3',
    [z, x, y],
  )
  assert.equal(kept.rows[0].n, 1, 'finished ground is kept')
})
