import assert from 'node:assert/strict'
import test from 'node:test'
import pg from 'pg'
import { buildServer } from '../src/app.js'
import { authenticate } from './auth-helper.js'
import { privateDatabase } from './private-database.js'

/* The three endpoints against real PostGIS, because everything that can go
 * quietly wrong here is a property of the database and not of the JavaScript:
 *
 *   The accent fold. `search_name` is generated by `place_searchable()` and
 *   the trigram index is on it. A query that folds any other way returns an
 *   empty list — not an error, an empty list — so "cafe zoom" finding
 *   "Café Zoöm" is the assertion that the index and the lookup agree, and it
 *   can only be made against the real function.
 *
 *   The redirects. A stop keeps a place id for the life of a trip and upstream
 *   reissues ids monthly. A merged place must still open by its old id, and a
 *   closed one must say it closed rather than 404 — two different answers a
 *   traveller can act on.
 *
 *   The widening. A sparse area must not return an empty list; the radius
 *   grows and the floor drops in the documented steps, and the response says
 *   which radius it ended up using.
 *
 * Its own database, named for this file rather than for the layer: this file
 * resets the schema, so does places-ingest.test.js, and the runner runs them
 * at the same time. Two files sharing one name here is three unrelated
 * assertions failing in whichever lost the race. See private-database.js.
 */

const baseUrl =
  process.env.TEST_DATABASE_URL || 'postgres://postgres:postgres@127.0.0.1:55432/wayfare_test'

const moduleUnderTest = await import('../src/postgres.js').catch(() => null)

let databaseUrl = baseUrl
const reachable = await (async () => {
  if (!moduleUnderTest) return 'no postgres module'
  const client = new pg.Client({ connectionString: baseUrl })
  try {
    await client.connect()
    await client.end()
  } catch {
    return 'no PostgreSQL to test against'
  }
  databaseUrl = await privateDatabase(baseUrl, 'placesapi')
  return false
})()

const AMSTERDAM = { lng: 4.8852, lat: 52.36, cell: 'N52E004' }
/* The middle of a one-degree cell on the prairies, so even the widest rung of
   the ladder stays inside one cell and the test is about widening rather than
   about coverage. */
const PRAIRIE = { lng: -105.5, lat: 50.5, cell: 'N50W106' }

/* Ten places above the confidence floor within a few hundred metres, because
   `widen` stops as soon as a rung finds eight: fewer and the happy path would
   be quietly testing the sparse path instead. */
const SEED = [
  ['Rijksmuseum', 'museum', 4.8852, 52.36, 0.93, 'art_museum'],
  ['Café Zoöm', 'cafe', 4.886, 52.3608, 0.71, 'coffee_shop'],
  ['Van Gogh Museum', 'museum', 4.8811, 52.3584, 0.88, 'art_museum'],
  ['Moco Museum', 'museum', 4.8817, 52.3591, 0.74, 'art_museum'],
  ['Museumplein', 'sights', 4.8796, 52.3576, 0.8, 'public_plaza'],
  ['Concertgebouw', 'entertainment', 4.8792, 52.3562, 0.86, 'concert_hall'],
  ['Stedelijk Museum', 'gallery', 4.8797, 52.358, 0.82, 'art_gallery'],
  ['Wasserette De Zeep', 'services', 4.8854, 52.3602, 0.64, 'laundry'],
  ['Broodje Van Gogh', 'food', 4.8843, 52.3597, 0.62, 'sandwich_shop'],
  ['Bar Vondel', 'bar', 4.8775, 52.3583, 0.69, 'bar'],
  /* Under the 0.3 floor: a duplicate or a defunct shop, and never shown. */
  ['Rijksmuseum (dup)', 'museum', 4.8853, 52.3601, 0.12, 'art_museum'],
]

async function seed(client) {
  const ids = new Map()
  for (const [name, category, lng, lat, confidence, raw] of SEED) {
    const inserted = await client.query(
      `insert into places
        (gers_id, name, alternate_names, geom, category, category_raw, address, website, phone,
         confidence, operating, cell)
       values ($1,$2,$3, ST_SetSRID(ST_MakePoint($4,$5),4326)::geography, $6,$7,$8::jsonb,$9,$10,$11,$12,$13)
       returning id`,
      [
        `overture:${name.toLowerCase().replaceAll(/[^a-z]+/g, '-')}`,
        name,
        [],
        lng,
        lat,
        category,
        raw,
        JSON.stringify({ freeform: 'Museumstraat 1', locality: 'Amsterdam', country: 'NL' }),
        null,
        null,
        confidence,
        'open',
        'N52E004',
      ],
    )
    ids.set(name, inserted.rows[0].id)
  }

  /* One grain elevator, six kilometres away, alone in its cell. */
  const prairie = await client.query(
    `insert into places (gers_id, name, geom, category, category_raw, confidence, cell)
     values ($1,$2, ST_SetSRID(ST_MakePoint($3,$4),4326)::geography, $5,$6,$7,$8) returning id`,
    [
      'overject:elevator',
      'Pioneer Grain Elevator',
      PRAIRIE.lng + 0.0847,
      PRAIRIE.lat,
      'historic',
      'historic_site',
      0.55,
      PRAIRIE.cell,
    ],
  )
  ids.set('Pioneer Grain Elevator', prairie.rows[0].id)

  /* Two sources on one record, one of them OpenStreetMap — which is the whole
     point of carrying the trail: ODbL obliges us to attribute and CDLA does
     not, and the response has to say which applies to which record. */
  await client.query(
    `insert into place_sources (place_id, source, license, upstream_id, version, confidence, fields)
     values ($1,'overture','CDLA-Permissive-2.0','ov-rijks','2026-08-19.0',0.93,'{name,category}'),
            ($1,'osm','ODbL-1.0','w12345','2026-08-19.0',0.9,'{website,phone}')`,
    [ids.get('Rijksmuseum')],
  )
  await client.query(
    `insert into place_sources (place_id, source, license, upstream_id, version, confidence, fields)
     values ($1,'overture','CDLA-Permissive-2.0','ov-zoom','2026-08-19.0',0.71,'{name}')`,
    [ids.get('Café Zoöm')],
  )

  for (const cell of [AMSTERDAM.cell, PRAIRIE.cell]) {
    const [ns, latitude, ew, longitude] = [
      cell[0],
      Number(cell.slice(1, 3)),
      cell[3],
      Number(cell.slice(4)),
    ]
    const south = (ns === 'S' ? -1 : 1) * latitude
    const west = (ew === 'W' ? -1 : 1) * longitude
    await client.query(
      `insert into place_coverage (cell, west, south, east, north, status, versions, place_count, last_refresh)
       values ($1,$2,$3,$4,$5,'ready','{"overture":"2026-08-19.0"}'::jsonb,$6, now())`,
      [cell, west, south, west + 1, south + 1, cell === AMSTERDAM.cell ? SEED.length : 1],
    )
  }
  return ids
}

async function world(t) {
  const admin = new pg.Client({ connectionString: databaseUrl })
  await admin.connect()
  await admin.query('drop schema public cascade; create schema public')
  await admin.end()

  const repository = await moduleUnderTest.createPostgresRepository({
    databaseUrl,
    adminEmail: 'owner@example.com',
  })
  t.after(() => repository.close())
  await repository.migrate()

  const client = new pg.Client({ connectionString: databaseUrl })
  await client.connect()
  t.after(() => client.end())
  const ids = await seed(client)

  const app = await buildServer({
    repository,
    mailer: { async send() {} },
    publicUrl: 'https://offwego.example.com',
    sessionSecret: 'test-secret-that-is-long-enough',
  })
  t.after(() => app.close())
  const authorization = await authenticate(repository, 'owner@example.com')
  const get = (url, headers = { authorization }) => app.inject({ method: 'GET', url, headers })
  return { app, repository, client, ids, authorization, get }
}

test('search finds a place by name, with its provenance', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get('/api/places/search?q=rijks')
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.degraded, false)
  assert.equal(body.places[0].name, 'Rijksmuseum')
  assert.equal(body.places[0].category, 'museum')
  assert.equal(body.places[0].confidence, 0.93)
  /* Every record says who told us and under what licence. */
  assert.deepEqual(
    body.places[0].sources.map(source => [source.source, source.license, source.upstreamId]),
    [
      ['osm', 'ODbL-1.0', 'w12345'],
      ['overture', 'CDLA-Permissive-2.0', 'ov-rijks'],
    ],
  )
  /* And the notices the client has to render — ODbL, because one of them is
     OpenStreetMap's. */
  assert.ok(
    body.places[0].attribution.some(
      notice => notice.license === 'ODbL-1.0' && /OpenStreetMap/.test(notice.notice),
    ),
    'ODbL notice travels with the record',
  )
  /* A typeahead is re-issued per keystroke; the cache is short and private. */
  assert.equal(response.headers['cache-control'], 'private, max-age=30')
})

test('search folds accents and case, both ways', { skip: reachable }, async t => {
  const { get } = await world(t)
  const plain = await get('/api/places/search?q=cafe%20zoom')
  assert.equal(plain.statusCode, 200)
  assert.equal(
    plain.json().places[0]?.name,
    'Café Zoöm',
    'unaccented letters find the accented name',
  )
  const accented = await get(`/api/places/search?q=${encodeURIComponent('CAFÉ ZOÖM')}`)
  assert.equal(accented.json().places[0]?.name, 'Café Zoöm', 'and the accented letters do too')
})

test('search biased to a trip still finds what is far away', { skip: reachable }, async t => {
  const { get, repository } = await world(t)
  const user = await repository.ensureUser('owner@example.com')
  const trip = await repository.createTrip(user, { title: 'Amsterdam' })
  await repository.createStop(user, trip.id, {
    name: 'Hotel',
    icon: 'pin',
    status: 'planned',
    lng: AMSTERDAM.lng,
    lat: AMSTERDAM.lat,
  })
  const near = await get(`/api/places/search?q=museum&trip_id=${trip.id}`)
  assert.equal(near.statusCode, 200)
  assert.ok(
    near.json().places.some(place => place.name === 'Van Gogh Museum'),
    'the trip geography is searched',
  )
  /* A trip nobody is on is not a search scope. */
  const other = await authenticate(repository, 'stranger@example.com')
  const refused = await get(`/api/places/search?q=museum&trip_id=${trip.id}`, {
    authorization: other,
  })
  assert.equal(refused.statusCode, 404)
})

test('nearby ranks by kind and distance together', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=1000`,
  )
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.degraded, false)
  assert.equal(body.widened, 0, 'ten places within the radius is enough')
  assert.equal(body.radius, 1000)
  const names = body.places.map(place => place.name)
  assert.equal(names[0], 'Rijksmuseum')
  /* The launderette is nearer than half the list and still below it. */
  assert.ok(
    names.indexOf('Wasserette De Zeep') > names.indexOf('Van Gogh Museum'),
    'a museum eight hundred metres away beats a launderette underfoot',
  )
  /* Under the floor is not shown at all, rather than shown last: a
     0.12-confidence duplicate on a map is worse than no pin. */
  assert.ok(!names.includes('Rijksmuseum (dup)'), 'the confidence floor suppresses, not demotes')
  assert.equal(response.headers['cache-control'], 'private, max-age=120')
  assert.ok(body.places.every(place => Number.isFinite(place.metres)))
})

test('nearby filters by category, and refuses one it does not know', {
  skip: reachable,
}, async t => {
  const { get } = await world(t)
  const museums = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=1000&category=museum`,
  )
  assert.equal(museums.statusCode, 200)
  assert.deepEqual(
    [...new Set(museums.json().places.map(place => place.category))],
    ['museum'],
    'only the category asked for',
  )
  const nonsense = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&category=nightclubs`,
  )
  assert.equal(nonsense.statusCode, 400)
})

test('a sparse area widens rather than returning nothing', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get(`/api/places/nearby?lat=${PRAIRIE.lat}&lng=${PRAIRIE.lng}&radius=1000`)
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.places.length, 1, 'the one real place, not an empty list and not an invention')
  assert.equal(body.places[0].name, 'Pioneer Grain Elevator')
  assert.ok(body.widened > 0, 'the ladder was climbed')
  assert.ok(body.radius > 1000, 'and the answer says how far it had to go')
  assert.ok(body.radius <= 50_000, 'but never past where "nearby" stops meaning anything')
})

test('a silly radius or limit is capped, not refused', { skip: reachable }, async t => {
  const { get } = await world(t)
  const response = await get(
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=9000000&limit=5000`,
  )
  assert.equal(response.statusCode, 200)
  assert.ok(response.json().radius <= 50_000)
  assert.ok(response.json().places.length <= 50)
  /* Letters where a number goes is a bug in the caller, and says so. */
  assert.equal((await get('/api/places/nearby?lat=here&lng=4.8')).statusCode, 400)
  assert.equal((await get('/api/places/nearby?lat=52.36')).statusCode, 400)
})

test('one place, in full, with its sources', { skip: reachable }, async t => {
  const { get, ids } = await world(t)
  const response = await get(`/api/places/${ids.get('Rijksmuseum')}`)
  assert.equal(response.statusCode, 200)
  const { place, redirectedFrom } = response.json()
  assert.equal(redirectedFrom, null)
  assert.equal(place.name, 'Rijksmuseum')
  assert.equal(place.address.locality, 'Amsterdam')
  assert.equal(place.sources.length, 2)
  assert.ok(place.attribution.length >= 2)
  /* A record changes with a monthly ingest; a day is already far shorter than
     the data's own life. */
  assert.equal(response.headers['cache-control'], 'private, max-age=86400')
  assert.equal((await get('/api/places/not a uuid at all')).statusCode, 400)
  assert.equal(
    (await get('/api/places/3f0c8f0e-1111-4111-8111-111111111111')).statusCode,
    404,
    'an id nobody has ever heard of is a plain not-found',
  )

  /* And the upstream id opens the same door, because it is the only id a
     degraded answer can carry: a stop filed from a fallback list must open
     once its cell has been ingested, without the client knowing which kind of
     answer it came from. */
  const byUpstream = await get(`/api/places/${encodeURIComponent(place.gersId)}`)
  assert.equal(byUpstream.statusCode, 200)
  assert.equal(byUpstream.json().place.id, ids.get('Rijksmuseum'))
  assert.equal((await get('/api/places/overture:nobody')).statusCode, 404)
})

test('a place that moved still resolves by its old id', { skip: reachable }, async t => {
  const { get, client, ids } = await world(t)
  const moved = '11111111-2222-4333-8444-555555555555'
  const alsoMoved = '11111111-2222-4333-8444-666666666666'
  /* Two dead ids pointing at one survivor, which is what a three-way merge
     leaves behind. Migration 043 makes `new_id` a foreign key into `places`,
     so a redirect can only ever point at a row that exists: a chain through a
     vanished intermediate is unrepresentable, and the hop limit in store.js is
     there against a bad ingest rather than against the normal case. */
  await client.query(
    `insert into place_redirects (old_id, new_id, reason) values ($1,$3,'merged'), ($2,$3,'merged')`,
    [moved, alsoMoved, ids.get('Rijksmuseum')],
  )
  for (const old of [moved, alsoMoved]) {
    const response = await get(`/api/places/${old}`)
    assert.equal(response.statusCode, 200)
    assert.equal(response.json().place.id, ids.get('Rijksmuseum'))
    assert.equal(response.json().redirectedFrom, old, 'and says which id it came in on')
    assert.ok(response.json().place.sources.length, 'the successor arrives whole')
  }
})

test('a place that closed says so, and does not 404', { skip: reachable }, async t => {
  const { get, client } = await world(t)
  const closed = '99999999-2222-4333-8444-555555555555'
  await client.query(
    `insert into place_redirects (old_id, new_id, reason) values ($1, null, 'closed')`,
    [closed],
  )
  const response = await get(`/api/places/${closed}`)
  assert.equal(response.statusCode, 410, 'gone, which is a different fact from never existed')
  assert.equal(response.json().gone, true)
  assert.equal(response.json().reason, 'closed')
})

test('every route is behind the same login as the rest of /api', { skip: reachable }, async t => {
  const { app, get, ids } = await world(t)
  for (const url of [
    '/api/places/search?q=rijks',
    `/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}`,
    `/api/places/${ids.get('Rijksmuseum')}`,
  ]) {
    const anonymous = await app.inject({ method: 'GET', url })
    assert.equal(anonymous.statusCode, 401, `${url} refuses an unsigned request`)
    assert.equal(anonymous.json().error, 'Sign in required')
    const wrong = await app.inject({
      method: 'GET',
      url,
      headers: { authorization: 'Bearer nonsense' },
    })
    assert.equal(wrong.statusCode, 401, `${url} refuses a bad token`)
  }
  assert.equal((await get('/api/places/search?q=rijks')).statusCode, 200)
})

test('an uncovered cell is asked for, and the answer says it is thin', {
  skip: reachable,
}, async t => {
  const { get, client } = await world(t)
  /* Tokyo: no coverage row at all, and nothing in `places`. */
  const response = await get('/api/places/nearby?lat=35.6586&lng=139.7454&radius=500')
  assert.equal(response.statusCode, 200)
  const body = response.json()
  assert.equal(body.degraded, true)
  assert.equal(body.coverage.cell, 'N35E139')
  assert.deepEqual(body.places, [])
  /* Degraded answers must not be cached: the cell is being ingested now. */
  assert.equal(response.headers['cache-control'], 'no-store')
  const queued = await client.query(
    'select cell, status, requested_at from place_coverage where cell=$1',
    ['N35E139'],
  )
  assert.equal(queued.rows[0].status, 'pending', 'the miss put the cell on the queue')
  assert.ok(queued.rows[0].requested_at, 'with the moment it was asked for, so it can be ordered')

  /* Asking again does not move it to the back of the queue. */
  const first = queued.rows[0].requested_at
  await get('/api/places/nearby?lat=35.6586&lng=139.7454&radius=500')
  const again = await client.query('select requested_at from place_coverage where cell=$1', [
    'N35E139',
  ])
  assert.deepEqual(again.rows[0].requested_at, first, 'requested_at keeps the earliest ask')
})

test('a ready cell is never knocked back to pending by a query', { skip: reachable }, async t => {
  const { get, client } = await world(t)
  await get(`/api/places/nearby?lat=${AMSTERDAM.lat}&lng=${AMSTERDAM.lng}&radius=1000`)
  const row = await client.query('select status from place_coverage where cell=$1', [
    AMSTERDAM.cell,
  ])
  assert.equal(row.rows[0].status, 'ready')
})
