/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as NewRouteImport } from './routes/new'
import { Route as PastRouteImport } from './routes/past'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AuthNativeRouteImport } from './routes/auth.native'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as UsersHandleRouteImport } from './routes/users.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PastRoute = PastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNativeRoute = AuthNativeRouteImport.update({
  id: '/auth/native',
  path: '/auth/native',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersHandleRoute = UsersHandleRouteImport.update({
  id: '/users/$handle',
  path: '/users/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/new': typeof NewRoute
  '/past': typeof PastRoute
  '/profile': typeof ProfileRoute
  '/auth/native': typeof AuthNativeRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/users/$handle': typeof UsersHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/new': typeof NewRoute
  '/past': typeof PastRoute
  '/profile': typeof ProfileRoute
  '/auth/native': typeof AuthNativeRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/users/$handle': typeof UsersHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/new': typeof NewRoute
  '/past': typeof PastRoute
  '/profile': typeof ProfileRoute
  '/auth/native': typeof AuthNativeRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/users/$handle': typeof UsersHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitations'
    | '/new'
    | '/past'
    | '/profile'
    | '/auth/native'
    | '/trips/$slug'
    | '/users/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitations'
    | '/new'
    | '/past'
    | '/profile'
    | '/auth/native'
    | '/trips/$slug'
    | '/users/$handle'
  id:
    | '__root__'
    | '/'
    | '/invitations'
    | '/new'
    | '/past'
    | '/profile'
    | '/auth/native'
    | '/trips/$slug'
    | '/users/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitationsRoute: typeof InvitationsRoute
  NewRoute: typeof NewRoute
  PastRoute: typeof PastRoute
  ProfileRoute: typeof ProfileRoute
  AuthNativeRoute: typeof AuthNativeRoute
  TripsSlugRoute: typeof TripsSlugRoute
  UsersHandleRoute: typeof UsersHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/native': {
      id: '/auth/native'
      path: '/auth/native'
      fullPath: '/auth/native'
      preLoaderRoute: typeof AuthNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$handle': {
      id: '/users/$handle'
      path: '/users/$handle'
      fullPath: '/users/$handle'
      preLoaderRoute: typeof UsersHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitationsRoute: InvitationsRoute,
  NewRoute: NewRoute,
  PastRoute: PastRoute,
  ProfileRoute: ProfileRoute,
  AuthNativeRoute: AuthNativeRoute,
  TripsSlugRoute: TripsSlugRoute,
  UsersHandleRoute: UsersHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
